[workspace]
members = [
    "packages/*",
    "contracts/core/*",
    "contracts/core/adapters/*",
    "contracts/gateway/*",
    "contracts/pylon/*",
]
exclude = [
    "contracts/core/adapters",
]

[profile.release]
rpath = false
lto = true
overflow-checks = true

